---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-", 
  dpi = 200,
  out.width = "100%"
)
```

# draw

<!-- badges: start -->
<!-- badges: end -->

A package to generate cartesian coordinates for various polygons, and to fill polygons with lines.

## Installation

You can install the development version of draw from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("robbrotherton/draw")
```

## Make shapes

```{r shapes, out.width='50%'}
library(draw)

circle() |> show()
square() |> show()
star() |> show()
polygon(sides = 6) |> show()
rectangle(width = 1.5, height = 1) |> show()
heart() |> show()

```

## Fill shapes

```{r fills, out.width='50%'}
circle() |> fill_hatch() |> show()
square() |> fill_hatch(angle = c(pi*.25, pi*.75)) |> show()
polygon(8) |> fill_wave() |> show()
heart() |> fill_zigzag() |> show()
star() |> fill_inset() |> show()
```


## Fill many shapes

```{r stars}
set.seed(1)

n <- 15

input <- data.frame(n = 1:n, 
                    radius = rnorm(n, mean = 10, sd = 2),
                    angle = runif(n, min = 0, max = 2*pi),
                    offset_x = runif(n, min = 0, max = 120),
                    offset_y = runif(n, min = 0, max = 200))

stars <- purrr::pmap(input, ~star(radius = ..2, angle = ..3) |> 
                             dplyr::mutate(x = x + ..4, y = y + ..5)) |>
  purrr::map2(.y = input$angle, .f = ~fill_hatch(.x, spacing = 1, angle = .y)) |> 
  dplyr::bind_rows(.id = "star") |> 
  dplyr::group_by(star, group) |> 
  dplyr::mutate(group = dplyr::cur_group_id())

show(stars, void = TRUE)

```


```{r square-grid}
dim <- c(12, 17)
n <- prod(dim)
angles <- sample(c(0, pi*.5, pi*.25, pi*.75), n, replace = TRUE)

square_grid <- shape_grid(square(), dim) |> 
  dplyr::group_by(group) |> 
  dplyr::group_split() |> 
  purrr::map2_df(.y = angles, .f = ~fill_hatch(.x, angle = .y), .id = "shape") |> 
  dplyr::group_by(shape, group) |> 
  dplyr::mutate(group = dplyr::cur_group_id())

show(square_grid, void = TRUE)

```

```{r circle-grid}

n <- 9^2
angles <- runif(n, 0, pi)

circle_grid <- shape_grid(circle(), n = n) |> 
  dplyr::group_by(group) |> 
  dplyr::group_split() |> 
  purrr::map2_df(.y = angles, .f = ~fill_hatch(.x, angle = .y), .id = "shape") |> 
  dplyr::group_by(shape, group) |> 
  dplyr::mutate(group = dplyr::cur_group_id())

show(circle_grid, void = TRUE)

```

